<div class='row' style= 'background-color:#000000;opacity: 0.8;color: #FFFFFF;'>


  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="cmi-tab-appitizer">
         <?php echo $this->partialLoop('food/menuitem-list.phtml', $this->appitizer);?>
    </div>
    <div role="tabpanel" class="tab-pane" id="cmi-tab-entry">
        <?php echo $this->partialLoop('food/menuitem-list.phtml', $this->entry);?>
    </div>
  </div>

</div>