<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<div class="footer">
    <div class="container">

        <div class="row">
            <div class ="clo-lg-4 col-md-4 col-sm-12">
                <div class="title">
                    Social Media
                </div>
                <div class="details">
                  <div class="fb-share-button" data-href="https://www.facebook.com/pages/Kafal-Himalayan-Fusion/1654368764800694?fref=photo" data-layout="button_count"></div>
                </div>
            </div>
            <div class ="clo-lg-4 col-md-4 col-sm-12">
                <div class="title">
                    Working Hours
                </div>
                <div class="details">
                    Depending on the guest and foods and days you can make your catering orders.
                </div>
            </div>
        
       
            <div class ="clo-lg-4 col-md-4 col-sm-12">
                <div class="title">
                    Address
                </div>
                <div class="details">
                    Depending on the guest and foods and days you can make your catering orders.
                </div>
            </div>
        </div>
    </div>
</div>