
<div class='col-md-2 menu'>
    
   <ul>
    	<li class="aboutus"><a href="/aboutus">About Us</a></li>
   		<li><a href="/drinks">Beer and Wine</a></li>
    	<li><a href="/lunch">Lunch</a></li>
    	<li><a href="/dinner">Dinner</a></li>
    	<li><a href="/gallery">Gallery</a></li>
    	<li><a href="/services">Service</a></li>
    	<li class="contact"><a href="/contactus">Contact Us</a></li>
	</ul>
</div>
