
<div class='col-md-2 menu'>
   <ul>
    	<li><a  class="cmi-mainnav about" href="#aboutus" >About Us</a></li>
   		<li><a  class="cmi-mainnav" href="#drinks">Beer and Wine</a></li>
    	<li><a  class="cmi-mainnav" href="#menu">Menu</a></li>
    	<li><a  class="cmi-mainnav" href="#gallery">Gallery</a></li>
    	<li><a  class="cmi-mainnav" href="#service">Service</a></li>
    	<li><a  class="cmi-mainnav" href="#contact">Contact Us</a></li>
	</ul>
</div>
