<nav class="navbar navbar-inverse cmi-header">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/" style="padding-top: 0px;"><img src="/img/logo.png" alt="logo"/ class='img-responsive'></a>
    </div>
    <div class="navigation">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li><a href="/menu">Menu</a></li>
        <li><a href="/gallery">Gallery</a></li>
        <li><a href="/contactus">Contact US</a></li>
      </ul>
    </div>
    <div class="clear"></div>
  </div>
</nav>


