<div class="title">
    <div class="container">
        <div class="row">
            <div class ="clo-lg-4 col-md-4 col-sm-12">
                <p class="logo"><img src="/img/logo.png" alt="logo"/ width="130"></p>
            </div>
            <div class ="clo-lg-8 col-md-8 col-sm-12">
                <ul class="subMenu">
                    <li class="underline">Home</li>
                    <li>Team</li>
                    <li><a href='/menu'>Menu</a></li>
                    <li>Contact US</li>
                </ul>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>