<!--    <div class="container">
        <div class="row">
            <div class ="clo-lg-7 col-md-6 col-sm-12">
                <p class="logo"><img src="/img/logo.png" alt="logo"/ width="300"></p>
            </div>
            <div class ="clo-lg-5 col-md-6 col-sm-12">
                <ul class="subMenu">
                    <li class="bold">Home</li>
                    <li>Team</li>
                    <li><a href='/menu'>Menu</a></li>
                    <li>Contact US</li>
                </ul>
            </div>
        </div>
    </div>
</div>-->


<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><img src="/img/logo.png" alt="logo"/ width="300"></a>
    </div>
    <div class="navigation">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li><a href="/menu">Menu</a></li>
        <li><a href="/gallery">Gallery</a></li>
        <li><a href="/contactus">Contact US</a></li>
      </ul>
    </div>
    <div class="clear"></div>
  </div>
</nav>

