<div class='col-md-3' style='color: #FFFFFF;'>
                    
                    <div class='cmi-container'>
                        <h4>LOCATION</h4>
                        <p>
                            535 Ross St</br>
                            Santa Rosa, CA, 96990<br>
                            Phone: <a href="tel:7075953311">(707) 595-3311</a>
                        </p>
                    </div>   
                    
                    <div class='cmi-container'>    
                        <h4>LUNCH HOURS</h4>
                        <p>
                            Mon - Fri : 11:30am - 2:30pm</br>
                            Sat - Sun : 12:00pm - 3:00pm
                        </p>
                     </div>     
                        
                     <div class='cmi-container'>   
                        <h4>DINNER HOURS</h4>
                        <p>
                            Sun - Thu : 5:00pm - 10:00pm</br>
                            Fri - Sat : 5:00pm - 10:30pm 
                        </p>
                     </div>  
                     
                     <div class='cmi-container'>   
                        <h4>HOME DELEVERY SERVICE</h4>
                        <p>
                           Over $25</br>
                        </p>
                     </div>  
                </div>