<?php 
    echo $this->doctype(); 
?>

<html lang="en">
    <?php echo $this->partial("/partial/head.phtml");?>
        
    <body>
        <?php 
            echo $this->partial("/partial/logoHeader.phtml");
        ?>
        <div class='container-fluid'>
            <div class='row'>
               <?php  
                    echo $this->partial("/partial/mainMenu.phtml");
                 ?>
                <div class='col-md-7 content'>
                    <div class='row hidden cmi-container-home back-img' id='cmi-container-aboutus'>
                        <div class='col-md-12'>
                            <?php echo $this->aboutus; ?>
                        </div>
                    </div>
                    <div class='row hidden cmi-container-home back-img' id='cmi-container-drinks'>
                        <div class='col-md-12'>
                            <?php echo $this->beer; ?>
                        </div>
                    </div>
                    <div class='row hidden cmi-container-home back-img' id='cmi-container-lunch'>
                        <div class='col-md-12'>
                            <?php echo $this->lunch; ?>
                        </div>
                    </div>
                    <div class='row hidden cmi-container-home back-img' id='cmi-container-dinner'>
                        <div class='col-md-12'>
                            <?php echo $this->dinner; ?>
                        </div>
                    </div>
                    <div class='row hidden cmi-container-home' id='cmi-container-gallery'>
                        <div class='col-md-12'>
                            <?php echo $this->gallery; ?>
                        </div>
                    </div>
                    <div class='row hidden cmi-container-home back-img' id='cmi-container-service'>
                        <div class='col-md-12'>
                            <?php echo $this->service; ?>
                        </div>
                    </div>
                    <div class='row hidden cmi-container-home' id='cmi-container-contact'>
                       <?php echo $this->contactus; ?>
                    </div>
                </div>
            
            <?php  
                echo $this->partial("/partial/sideContent.phtml");
             ?>
        </div>
       </div>     
    </body>
</html>
