<?php 
    echo $this->doctype(); 
?>

<html lang="en">
    <?php echo $this->partial("/partial/head.phtml");?>
        
    <body>
        <?php 
            //echo $this->partial("/partial/navigation.phtml");
        ?>
        
            <div class='row' style='background-color: #000000';>
                
                <div class='logo' style='text-align: center;'>
                        <img src='/img/logo_olg.png' style='height:150px;' />
                    
                    </div>
            
            </div>
            <div class='row'>
                <div class='col-md-2' style='background-color: #000000;height:1000px;'>
                    
                   <ul style='color: #FFFFFF;font-weight:100;font-size: 20px;'>
                    <li style='border-bottom: 1px solid #FFFFFF;padding-bottom:5px;padding-top: 5px;'><a href='#' style='color: #FFFFFF;font-weight:100;font-size: 20px;'>About Us</a></li>
                    <li style='border-bottom: 1px solid #FFFFFF;padding-bottom:5px;padding-top: 5px;'><a href='#' style='color: #FFFFFF;font-weight:100;font-size: 20px;'>Beer and Wine</a></li>
                    <li style='border-bottom: 1px solid #FFFFFF;padding-bottom:5px;padding-top: 5px;'><a href='#' style='color: #FFFFFF;font-weight:100;font-size: 20px;'>Lunch</a></li>
                    <li style='border-bottom: 1px solid #FFFFFF;padding-bottom:5px;padding-top: 5px;'><a href='#' style='color: #FFFFFF;font-weight:100;font-size: 20px;'>Dinner</a></li>
                    <li style='border-bottom: 1px solid #FFFFFF;padding-bottom:5px;padding-top: 5px;'><a href='#' style='color: #FFFFFF;font-weight:100;font-size: 20px;'>Gallery</a></li>
                    <li style='border-bottom: 1px solid #FFFFFF;padding-bottom:5px;padding-top: 5px;'><a href='#' style='color: #FFFFFF;font-weight:100;font-size: 20px;'>Available Service</a></li>
                    <li style='border-bottom: 1px solid #FFFFFF;padding-bottom:5px;padding-top: 5px;'><a href='#' style='color: #FFFFFF;font-weight:100;font-size: 20px;'>Contact Us</a></li>
                    
                    
                    
                   </ul>
                </div>
                
                <div class='col-md-7' style="background-image: url('http://american.expert/wp-content/uploads/2015/03/cibo-indiano-1.jpg')">
                    <div>
                    <?php echo $this->foodItems; ?>
                    </div>
                </div>
                
                <div class='col-md-3' style='background-color: #000000;height:1000px;color: #FFFFFF;'>
                    
                    <div class='cmi-container'>
                        <h4>LOCATION</h4>
                        <p>
                            25 Yerba Buena Lane</br>
                            San Francisco CA 94103<br>
                            Phone: 415-777-0500
                        </p>
                    </div>   
                    
                    <div class='cmi-container'>    
                        <h4>LUNCH HOURS</h4>
                        <p>
                            Mon - Fri : 11:30am - 2:30pm</br>
                            Sat - Sun : 12:00pm - 3:00pm
                        </p>
                     </div>     
                        
                     <div class='cmi-container'>   
                        <h4>DINNER HOURS</h4>
                        <p>
                            Sun - Thu : 5:00pm - 10:00pm</br>
                            Fri - Sat : 5:00pm - 10:30pm 
                        </p>
                     </div>  
                     
                     <div class='cmi-container'>   
                        <h4>HOME DELEVERY SERVICE</h4>
                        <p>
                           Over $25</br>
                        </p>
                     </div>  
                </div>
                 
            </div>
        

    </body>
</html>
