<?php 
    echo $this->doctype(); 
?>

<html lang="en">
    <?php echo $this->partial("/partial/head.phtml");?>
        
    <body>
        <?php 
            echo $this->partial("/partial/logoHeader.phtml");
        ?>
        <div class='row'>
           <?php  
                echo $this->partial("/partial/mainMenu.phtml");
             ?>
            <div class='col-md-7 content'>
                <div>
                    <?php echo $this->foodItems; ?>
                </div>
            </div>
            <?php  
                echo $this->partial("/partial/sideContent.phtml");
             ?>
        </div>
    </body>
</html>
