<?php 
    echo $this->doctype(); 
?>

<html lang="en">
    <?php echo $this->partial("/partial/head.phtml");?>
        
    <body style='background-color: #000000'>
        <?php 
            echo $this->partial("/partial/navigation.phtml");
        ?>
        
        
        <div class="container">
            <div class='row'>
                <div class='col-md-9'>
                    <div class="imageSection">
                        <img class="img-responsive" src="/img/kafal.jpg" alt="kafal">
                    </div>
                </div>
                 <div class='col-md-3'>
                    <div class='cmi-container'>
                        <h4>LOCATION</h4>
                        <p>
                            25 Yerba Buena Lane</br>
                            San Francisco CA 94103<br>
                            Phone: 415-777-0500
                        </p>
                    </div>   
                    
                    <div class='cmi-container'>    
                        <h4>LUNCH HOURS</h4>
                        <p>
                            Mon - Fri : 11:30am - 2:30pm</br>
                            Sat - Sun : 12:00pm - 3:00pm
                        </p>
                     </div>     
                        
                     <div class='cmi-container'>   
                        <h4>DINNER HOURS</h4>
                        <p>
                            Sun - Thu : 5:00pm - 10:00pm</br>
                            Fri - Sat : 5:00pm - 10:30pm 
                        </p>
                     </div>     
                    </div>
                </div>
            </div>
        </div>
        
        <div class="midBanner">
            <div class="container">
                <div class="row">
                    <p class="welcome">Welcome to Kafal Resturant</p>
                    <p class="cusine">Special in Indian and Nepali Cusine</p>
                </div>
            </div>
        </div>
    
        <div class="detailSection">
            <div class="container">
                <?php echo $this->foodItems; ?>
               
            </div>
        </div>
        <?php echo $this->partial("/partial/footer.phtml");?>

</body>
</html>
