<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/base.css'))
                        //->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="main">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <ul class="titleMenu">
                          <li class="selected">Home</li>
                          <li>Santa Rosa</li>
                        </ul>
                     </div>
                 </div>
             </div>
        </div>
        <div class="title">
            <div class="container">
                <div class="row">
                    <div class ="clo-lg-4 col-md-4 col-sm-12">
                        <p class="logo"><img src="../kafal/assets/image/logo.png" alt="logo"/ width="130"></p>
                    </div>
                    <div class ="clo-lg-8 col-md-8 col-sm-12">
                        <ul class="subMenu">
                            <li class="underline">Home</li>
                            <li>Team</li>
                            <li>Menu</li>
                            <li>Contact US</li>
                        </ul>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="imageSection">
            <img src="../kafal/assets/image/kafal.jpg" alt="kafal" width="100%">
        </div>
        <div class="midBanner">
            <div class="container">
                <div class="row">
                    <p class="welcome">Welcome to Kafal Resturant</p>
                    <p>Special in Indian and Nepali Cusine</p>
                </div>
            </div>
        </div>
    
        <div class="detailSection">
            <div class="container">
                <div class="row">
                    <div class ="clo-lg-4 col-md-4 col-sm-12">
                        <div class="title">
                            Catering
                        </div>
                        <div class="subTitle">
                            You can make catering orders
                        </div>
                        <img src="../kafal/assets/image/kafal.jpg" alt="kafal" width="100%">
                        <div class="detials">
                            Depending on the guest and foods and days you can make your catering orders.
                        </div>
                    </div>
                    <div class ="clo-lg-4 col-md-4 col-sm-12">
                        <div class="title">
                            Catering
                        </div>
                        <div class="subTitle">
                            You can make catering orders
                        </div>
                        <img src="../kafal/assets/image/kafal.jpg" alt="kafal" width="100%">
                        <div class="detials">
                            Depending on the guest and foods and days you can make your catering orders.
                        </div>
                    </div>
                    <div class ="clo-lg-4 col-md-4 col-sm-12">
                        <div class="title">
                            Catering
                        </div>
                        <div class="subTitle">
                            You can make catering orders
                        </div>
                        <img src="../kafal/assets/image/kafal.jpg" alt="kafal" width="100%">
                        <div class="detials">
                            Depending on the guest and foods and days you can make your catering orders.
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class ="clo-lg-4 col-md-4 col-sm-12">
                        <div class="title">
                            Catering
                        </div>
                        <div class="subTitle">
                            You can make catering orders
                        </div>
                        <img src="../kafal/assets/image/kafal.jpg" alt="kafal" width="100%">
                        <div class="detials">
                            Depending on the guest and foods and days you can make your catering orders.
                        </div>
                    </div>
                    <div class ="clo-lg-4 col-md-4 col-sm-12">
                        <div class="title">
                            Catering
                        </div>
                        <div class="subTitle">
                            You can make catering orders
                        </div>
                        <img src="../kafal/assets/image/kafal.jpg" alt="kafal" width="100%">
                        <div class="detials">
                            Depending on the guest and foods and days you can make your catering orders.
                        </div>
                    </div>
                    <div class ="clo-lg-4 col-md-4 col-sm-12">
                        <div class="title">
                            Catering
                        </div>
                        <div class="subTitle">
                            You can make catering orders
                        </div>
                        <img src="../kafal/assets/image/kafal.jpg" alt="kafal" width="100%">
                        <div class="detials">
                            Depending on the guest and foods and days you can make your catering orders.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer">
            <div class="container">
                <div class="row">
                </div>
            </div>
        </div>

</body>
</html>
