<?php 
    echo $this->doctype(); 
?>

<html lang="en">
    <?php echo $this->partial("/partial/head.phtml");?>
    <body>
        <?php 
            echo $this->partial("/partial/header.phtml");
            echo $this->partial("/partial/navigation.phtml");
        ?>
    
        <div class="detailSection">
            <div class="container">
                <?php echo $this->footItems; ?>
               
            </div>
        </div>
        <div class="footer">
            <div class="container">
                <div class="row">
                </div>
            </div>
        </div>

</body>
</html>
