<?php 
    echo $this->doctype(); 
?>

<html lang="en">
    <?php echo $this->partial("/partial/head.phtml");?>
        
    <body>
        <div class='container-fluid'>
            <div class='row'>
              <div class='col-md-12'>
                <img class='img-responsive' src='/img/under_construction.jpeg' />
              </div>
            </div>   
        </div>
       </div>     
    </body>
</html>
