<div class="col-lg-4 col-md-4 col-sm-12">
	<div class="cmi-container-service">
		<h4>Catering Service</h4>
		<img src='http://www.pridehotel.com/images/catering_1.jpg' class='img-responsive' />
		<p>We provide catering service. Call us for booking on <a href="tel:7075953311">(707) 595-3311</a> number.</p>
	</div>
</div>

<div class="col-lg-4 col-md-4 col-sm-12">
	<div class="cmi-container-service">
		<h4>Reservation</h4>
		<img src='http://www.lithosgreekrestaurant.com/images/reserve-inner-banner.jpg' class='img-responsive' />
		<p> Call us for reservation on <a href="tel:7075953311">(707) 595-3311</a> number.</p>
	</div>
</div>

<div class="col-lg-4 col-md-4 col-sm-12">
	<div class="cmi-container-service">
		<h4>Food Delivery</h4>
		<img src='https://justeatisb.files.wordpress.com/2014/12/food-delivery.jpg' class='img-responsive' />
		<p>We do free delivery for $25+ order withing 5 Mile radius.</p>
	</div>
</div>
