<div class="col-lg-4 col-md-4 col-sm-12">
	<div class="cmi-container-service">
		<h4>Catering Service</h4>
		<img src='http://www.pridehotel.com/images/catering_1.jpg' class='img-responsive' />
		<p>Bla Bla Bla about catering service. Call us for reservation on this number.</p>
	</div>
</div>

<div class="col-lg-4 col-md-4 col-sm-12">
	<div class="cmi-container-service">
		<h4>Reservation</h4>
		<img src='http://www.lithosgreekrestaurant.com/images/reserve-inner-banner.jpg' class='img-responsive' />
		<p>Bla Bla Bla about reservation. Call us for reservation on this number.</p>
	</div>
</div>

<div class="col-lg-4 col-md-4 col-sm-12">
	<div class="cmi-container-service">
		<h4>Food Delivery</h4>
		<img src='https://justeatisb.files.wordpress.com/2014/12/food-delivery.jpg' class='img-responsive' />
		<p>We do free delivery withing 5 Mile radius.</p>
	</div>
</div>
